# Generated by Django 5.2.14 on 2026-05-10 02:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_grade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['lab_group'], name='users_profi_lab_gro_0add93_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['grade'], name='users_profi_grade_25dd3d_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_dashboard_visible'], name='users_profi_is_dash_d1b623_idx'),
        ),
    ]
