# Generated by Django 4.2.16 on 2026-04-23 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usagelog',
            new_name='usage_usage_request_5de895_idx',
            old_name='usage_usagel_request_9b0990_idx',
        ),
        migrations.RenameIndex(
            model_name='usagelog',
            new_name='usage_usage_user_id_df7eb9_idx',
            old_name='usage_usagel_user_id_1ba868_idx',
        ),
        migrations.RenameIndex(
            model_name='usagelog',
            new_name='usage_usage_api_key_4085af_idx',
            old_name='usage_usagel_api_key_0e2f8a_idx',
        ),
    ]
