# Generated by Django 5.2.14 on 2026-05-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0002_rename_usage_usagel_request_9b0990_idx_usage_usage_request_5de895_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagelog',
            name='cached_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usagelog',
            name='latency_ms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usagelog',
            name='provider',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='usagelog',
            name='reasoning_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
