# Generated by Django 5.2.14 on 2026-05-10 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_modelpricing'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyusagestat',
            unique_together={('stat_date', 'model_name')},
        ),
    ]
